server:
  port: 9002                        # 服务端口，确保与其它微服务不冲突

spring:
  application:
    name: coupon-service        # 服务名称，注册到Nacos时的标识，需保持唯一

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.128:3306/shop-coupon?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234

  redis:
    host: 192.168.100.128
    password: 123456
    port: 8000

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.128:8848
  rabbitmq:
    host: 192.168.100.128      # RabbitMQ服务器IP
    port: 5672                  # AMQP端口
    virtual-host: /             # 虚拟主机（默认是 /）
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual  # 手动ACK模式，确保消息不丢失

  cache:
    type: redis    # 明确指定使用Redis作为缓存后端
# MyBatis-Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印SQL日志

logging:
  level:
    root: INFO                        # 全局日志级别


     # 将事务分组映射到TC集群



mqconfig:
  coupon_release_delay_queue: coupon.release.delay.queue
  coupon_release_queue: coupon.release.queue
  coupon_event_exchange: coupon.event.exchange
  coupon_release_delay_routing_key: coupon.release.delay.routing.key
  coupon_release_routing_key: coupon.release.routing.key
  ttl: 180000  # 测试15秒，生产改为 1920000 (32分钟)